### ISSUE TITLE
Error 404 when building docker image.

### ISSUE THREAD

**Issue by gjeempe** [FoRTu/docker-quake2-opentdm#1]
Hi. I'm not a specialist - just a gamer who want to learn docker and host q2 server. 
I found this problem in my journey with building an image. 
It looks like file not exist anymore. Is there a way that I will be able to change/point Dockerfile to a different place with deb package?
I own a server, so I can host this package until I'm alive. 

`--2021-03-06 11:14:10--  http://files.fortu.io/quake2-opentdm-server_8012-7402f92_amd64.deb
Resolving files.fortu.io (files.fortu.io)... 188.166.71.230
Connecting to files.fortu.io (files.fortu.io)|188.166.71.230|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-03-06 11:14:10 ERROR 404: Not Found.`

**Comment by FoRTu** [comment]
@gjeempe Thank for your report.

I have been changing some configurations my web server for improve security and I forgot this link. Now is fixed, so please, pull down the last changes and try to build it again. 

I have tested and now the image building process don't crash, but if you have any other issue or doubt about, don't hesitate to open a new issue.

**Comment by gjeempe** [comment]
I was able to pull and build image without any problems now. 

Thank you very, very much @FoRTu for your time and effort!
